<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Fri, 10 Feb 2017 13:34:50 +0000
 */

$conf['title'] = 'My Notes 2.1.1';
$conf['license'] = 'cc-by-sa';
$conf['maxtoclevel'] = '4';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
