<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Fri, 10 Feb 2017 01:19:59 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
